version: "3.9"

services:
  stock-app:
    build: .
    container_name: stock_predictor_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0

    restart: unless-stopped 